#server:
#  port : 0786
#  
#  spring.jpa:
#  database: MYSQL
#  hibernate.ddl-auto: create-drop
#  show-sql: true
#
#spring.datasource:
#  platform: mysql
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/userdatabase
#  username: root
#  password: 
#    hibernate:
#    dialect: com.x.data.core.hibernate.dialect.ExtendedH2Dialect